name: Lint & Test PR
on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]
jobs: 
  build:
    strategy:
      matrix:
        command: [lint, test]  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
      - run: npm run ${{ matrix.command }}